# Generated by Django 4.1.3 on 2024-06-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('cod_equipo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nom_equipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'equipo',
                'ordering': ['nom_equipo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('cod_fase', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nom_fase', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'fase',
                'ordering': ['cod_fase'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finalistas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'finalistas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marcador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('marcador1', models.IntegerField(blank=True, null=True)),
                ('marcador2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marcador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('nro_partido', models.IntegerField(primary_key=True, serialize=False)),
                ('nro_fecha', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('marcador1', models.IntegerField(blank=True, null=True)),
                ('marcador2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partido',
                'ordering': ['nro_partido'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCalculo',
            fields=[
                ('usuario', models.IntegerField(blank=True, null=True)),
                ('nom_usuario', models.TextField(blank=True, null=True)),
                ('nom_fase', models.TextField(blank=True, null=True)),
                ('nro_partido', models.IntegerField(primary_key=True, serialize=False)),
                ('equipo1', models.TextField(blank=True, null=True)),
                ('equipo2', models.TextField(blank=True, null=True)),
                ('marcador1', models.TextField(blank=True, null=True)),
                ('marcador2', models.TextField(blank=True, null=True)),
                ('resultado1', models.IntegerField(blank=True, null=True)),
                ('resultado2', models.IntegerField(blank=True, null=True)),
                ('dif1', models.TextField(blank=True, null=True)),
                ('dif2', models.TextField(blank=True, null=True)),
                ('difr', models.TextField(blank=True, null=True)),
                ('difm', models.TextField(blank=True, null=True)),
                ('tendencia', models.TextField(blank=True, null=True)),
                ('goles1', models.TextField(blank=True, null=True)),
                ('goles2', models.TextField(blank=True, null=True)),
                ('difgol', models.TextField(blank=True, null=True)),
                ('puntos', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_calculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCuadroHonor',
            fields=[
                ('usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_usuario', models.TextField(blank=True, null=True)),
                ('campeon', models.TextField(blank=True, null=True)),
                ('nom_campeon', models.TextField(blank=True, null=True)),
                ('puntos_campeon', models.TextField(blank=True, null=True)),
                ('subcampeon', models.TextField(blank=True, null=True)),
                ('nom_subcampeon', models.TextField(blank=True, null=True)),
                ('puntos_subcampeon', models.TextField(blank=True, null=True)),
                ('tercero', models.TextField(blank=True, null=True)),
                ('nom_tercero', models.TextField(blank=True, null=True)),
                ('puntos_tercero', models.TextField(blank=True, null=True)),
                ('cuarto', models.TextField(blank=True, null=True)),
                ('nom_cuarto', models.TextField(blank=True, null=True)),
                ('puntos_cuarto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_cuadro_honor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewMarcador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField(blank=True, null=True)),
                ('nom_usuario', models.TextField(blank=True, null=True)),
                ('nro_partido', models.IntegerField(blank=True, null=True)),
                ('nom_fase', models.CharField(blank=True, max_length=20, null=True)),
                ('nro_fecha', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('equipo1', models.CharField(blank=True, max_length=20, null=True)),
                ('equipo2', models.CharField(blank=True, max_length=20, null=True)),
                ('marcador1', models.TextField(blank=True, null=True)),
                ('marcador2', models.TextField(blank=True, null=True)),
                ('resultado1', models.IntegerField(blank=True, null=True)),
                ('resultado2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_marcador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewPartido',
            fields=[
                ('nro_partido', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_fase', models.CharField(blank=True, max_length=20, null=True)),
                ('nro_fecha', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('equipo1', models.CharField(blank=True, max_length=20, null=True)),
                ('equipo2', models.CharField(blank=True, max_length=20, null=True)),
                ('marcador1', models.TextField(blank=True, null=True)),
                ('marcador2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_partido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewPosiciones',
            fields=[
                ('num', models.BigIntegerField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField(blank=True, null=True)),
                ('nom_usuario', models.TextField(blank=True, null=True)),
                ('puntos', models.BigIntegerField(blank=True, null=True)),
                ('puntos_5', models.BigIntegerField(blank=True, null=True)),
                ('puntos_3', models.BigIntegerField(blank=True, null=True)),
                ('puntos_0', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_posiciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewPosicionesPlayOff',
            fields=[
                ('num', models.BigIntegerField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField(blank=True, null=True)),
                ('nom_usuario', models.TextField(blank=True, null=True)),
                ('puntos', models.BigIntegerField(blank=True, null=True)),
                ('puntos_5', models.BigIntegerField(blank=True, null=True)),
                ('puntos_3', models.BigIntegerField(blank=True, null=True)),
                ('puntos_0', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_posiciones_playoff',
                'managed': False,
            },
        ),
    ]
