# Generated by Django 4.1.3 on 2024-06-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_polla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estado',
                'ordering': ['id_estado'],
                'managed': False,
            },
        ),
    ]
